# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_inventory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='is_active',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
